# Generated by Django 5.2.6 on 2025-09-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pub_b2b", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("contact_email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("password", models.TextField(max_length=255)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("brewery", "Brewery"),
                            ("bakery", "Bakery"),
                            ("Butchers", "Butchers"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
