# Generated by Django 5.2.6 on 2025-09-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pub_b2b", "0002_supplier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="retailer",
            name="id",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="id",
        ),
        migrations.AddField(
            model_name="retailer",
            name="retailer_account_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="supplier",
            name="supplier_account_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
