# Generated by Django 5.2.6 on 2025-09-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pub_b2b", "0003_remove_retailer_id_remove_supplier_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "Product_ID",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("Product_name", models.CharField(max_length=255)),
                (
                    "storage_type",
                    models.CharField(
                        choices=[
                            ("Barrel", "BARREL"),
                            ("Bottle", "BOTTLE"),
                            ("Crate", "CRATE"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("Lager", "LAGER"),
                            ("Cider", "CIDER"),
                            ("Stout", "STOUT"),
                            ("Ale", "ALE"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
