# Generated by Django 5.2.6 on 2025-09-22 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pub_b2b", "0004_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="Product_ID",
            new_name="Product_id",
        ),
        migrations.CreateModel(
            name="Product_listing",
            fields=[
                ("p_listing_id", models.AutoField(primary_key=True, serialize=False)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity_available", models.IntegerField()),
                ("beverage_name", models.CharField(max_length=255)),
                ("beverage_type", models.CharField(max_length=255)),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pub_b2b.product",
                    ),
                ),
                (
                    "supplier_account_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pub_b2b.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("stock_id", models.AutoField(primary_key=True, serialize=False)),
                ("beverage_name", models.CharField(max_length=255)),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pub_b2b.product",
                    ),
                ),
                (
                    "retailer_account_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pub_b2b.retailer",
                    ),
                ),
            ],
        ),
    ]
