# Generated by Django 5.2.6 on 2025-09-22 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pub_b2b",
            "0005_rename_product_id_product_product_id_product_listing_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Retail_listing",
            fields=[
                ("r_listing_id", models.AutoField(primary_key=True, serialize=False)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "beverage_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("beverage_type", models.CharField(max_length=255)),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pub_b2b.product",
                    ),
                ),
                (
                    "retailer_account_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pub_b2b.retailer",
                    ),
                ),
            ],
        ),
    ]
